# Star Dataset Analysis

## Dataset Overview

This notebook provides an overview of the star dataset, including its structure, features, and basic descriptive statistics.

In [186]:
import pandas as pd
import numpy as np

## Load The Dataset

In [217]:
df = pd.read_csv("../data/Stars.csv.xls")

## First Look

In [218]:
df.head()

   Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

In [219]:
df.shape

(240, 7)

## Dataset Information

In [220]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Temperature     240 non-null    int64
 1   L               240 non-null    float64
 2   R               240 non-null    float64
 3   A_M             240 non-null    float64
 4   Color           240 non-null    str
 5   Spectral_Class  240 non-null    str
 6   Type            240 non-null    int64
dtypes: float64(3), int64(2), str(2)
memory usage: 13.3 KB

## Statistical Summary

In [221]:
df.describe()

        Temperature              L            R         A_M        Type
count    240.000000     240.000000   240.000000  240.000000  240.000000
mean   10497.462500  107188.361635   237.157781    4.382396    2.500000
std     9552.425037  179432.244940   517.155763   10.532512    1.711394
min     1939.000000       0.000080     0.008400  -11.920000    0.000000
25%     3344.250000       0.000865     0.102750   -6.232500    1.000000
50%     5776.000000       0.070500     0.762500    8.313000    2.500000
75%    15055.500000  198050.000000    42.750000   13.697500    4.000000
max    40000.000000  849420.000000  1948.500000   20.060000    5.000000

## Missing Values

In [222]:
df.isnull().sum()

Temperature       0
L                 0
R                 0
A_M               0
Color             0
Spectral_Class    0
Type              0
dtype: int64

## Duplicated Rows

In [223]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 0

## Basic Statistics

# Minimum temperature & Maximum temperature & Average temperature

In [224]:
print(f"Minimum temperature: {df["Temperature"].min()} K")

print(f"Maximum temperature: {df["Temperature"].max()} K")

mean = df["Temperature"].mean()
print(f"erage temperature: {np.round(mean, 3)}")

Minimum temperature: 1939 K
Maximum temperature: 40000 K
erage temperature: 10497.462

# Minimum luminosity & Maximum luminosity & Average luminosity

In [225]:
min_luminositydf = df["L"].min()
print(f"Minimum luminosity: {min_luminositydf}")

max_luminositydf = df["L"].max()
print(f"maximum luminosity: {max_luminositydf}")

print(f"Average luminosity: {np.round(df["L"].mean(), 3)}")

Minimum luminosity: 8e-05
maximum luminosity: 849420.0
Average luminosity: 107188.362

# Minimum radius & Maximum radius & Average radius

In [226]:
print(f"Minimum radius: {df["R"].min()}")

print(f"Maximum radius: {df["R"].max()}")

print(f"Average radius: {np.round(df["R"].mean(), 3)}")

Minimum radius: 0.0084
Maximum radius: 1948.5
Average radius: 237.158

## Category Distributions

# Star Type counts

In [227]:
df["Type"].value_counts()

Type
0    40
1    40
2    40
3    40
4    40
5    40
Name: count, dtype: int64

# Star Color counts

In [228]:
df["Color"].value_counts()

Color
Red                   112
Blue                   56
Blue-white             26
Blue White             10
yellow-white            8
White                   7
Blue white              4
Yellowish White         3
white                   3
Whitish                 2
Orange                  2
yellowish               2
Pale yellow orange      1
White-Yellow            1
Yellowish               1
Orange-Red              1
Blue-White              1
Name: count, dtype: int64

Observation:
Some star colors are written in different formats. These inconsistencies may affect the analysis, so they should be standardized.

In [229]:
df["Color"] = df["Color"].replace(
    {
    "Blue-white": "Blue White",
    "Blue white": "Blue White",
    "Blue-White": "Blue White",

    "white": "White",

    "yellowish": "Yellowish",

    "yellow-white": "Yellow White",

    "White-Yellow": "White Yellow",

    "Pale yellow orange": "Pale Yellow Orange",

    "Orange-Red": "Orange Red"
}
)

In [230]:
df["Color"].value_counts()

Color
Red                   112
Blue                   56
Blue White             41
White                  10
Yellow White            8
Yellowish White         3
Yellowish               3
Whitish                 2
Orange                  2
Pale Yellow Orange      1
White Yellow            1
Orange Red              1
Name: count, dtype: int64

# Spectral Class counts

In [231]:
df["Spectral_Class"].value_counts()

Spectral_Class
M    111
B     46
O     40
A     19
F     17
K      6
G      1
Name: count, dtype: int64

## Summary

- The dataset contains no missing values.
- No duplicate rows were found.
- Some color names required standardization.
- The dataset is ready for further analysis.